services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  game-server:
    image: ghcr.io/danilobez/client-server-applications-java-final-project:latest
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TCP_PORT=10000
      - HTTP_PORT=8080
    ports:
      - "${TCP_PORT}:10000"
      - "${HTTP_PORT}:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: